apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: ci-cd-pipeline

spec:
  project: default

  source:
    repoURL: https://github.com/0xJeevs/CI-CD-Pipeline.git
    targetRevision: HEAD
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
