apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: flask-app
        image: 996680283278.dkr.ecr.us-east-1.amazonaws.com/flask-app:63ffae30b30dcf985be2a15341f9d0040d3aa727
        ports:
        - containerPort: 5000
