apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: flask-app
        image:996680283278.dkr.ecr.us-east-1.amazonaws.com/flask-app:80072beb6084e360ccd3b70e816f8d9575c5dfa6
        ports:
        - containerPort: 5000
