apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: flask-app
        image:996680283278.dkr.ecr.us-east-1.amazonaws.com/flask-app:4deb3753d6038c0e460997aa397fc5cf3f4e34b3
        ports:
        - containerPort: 5000
